// <auto-generated />
using FieldOps.Modules.Employees.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FieldOps.Modules.Employees.Data.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    partial class EmployeesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FieldOps.Modules.Employees.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Org1 Admin",
                            OrganizationId = 1,
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Org1 Member",
                            OrganizationId = 1,
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Org2 Admin",
                            OrganizationId = 2,
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Org2 Member",
                            OrganizationId = 2,
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Orphaned Admin",
                            OrganizationId = 999,
                            Role = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
